/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewsParamPanel.java
 *
 * Created on Dec 8, 2011, 11:16:17 PM
 */

package websiteschema.analyzer.sample;

/**
 *
 * @author ray
 */
public class NewsParamPanel extends javax.swing.JPanel implements ISiteAnalyzer {

    String siteId;

    /** Creates new form NewsParamPanel */
    public NewsParamPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        siteIdLabel = new javax.swing.JLabel();

        jLabel1.setText("SiteId:");

        siteIdLabel.setText("siteId here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siteIdLabel)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(siteIdLabel))
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel siteIdLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setSiteId(String siteId) {
        this.siteId = siteId;
        this.siteIdLabel.setText(siteId);
    }

    @Override
    public String getSiteId(){
        return siteId;
    }
}
