/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PageInfoPanel.java
 *
 * Created on Dec 6, 2011, 11:31:13 PM
 */
package websiteschema.analyzer.browser.bottom;

import com.webrenderer.swing.dom.IDocument;
import java.util.Map;
import java.util.Set;
import websiteschema.context.BrowserContext;

/**
 *
 * @author ray
 */
public class PageInfoPanel extends javax.swing.JPanel {

    BrowserContext context;
    Map<String, String> urlAndMIME;

    /** Creates new form PageInfoPanel */
    public PageInfoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        charsetField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        urlArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        MIMEArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        contentTypeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sessionField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        cookieArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contentTypeFilterField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("Charset:");

        charsetField.setText("UTF-8");

        urlArea.setColumns(20);
        urlArea.setEditable(false);
        urlArea.setRows(5);
        urlArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urlArea);

        jLabel2.setText("HTTPResponse with MIME Message:");

        jLabel3.setText("URL:");

        MIMEArea.setColumns(20);
        MIMEArea.setEditable(false);
        MIMEArea.setRows(5);
        jScrollPane2.setViewportView(MIMEArea);

        jLabel4.setText("Content-Type: ");

        contentTypeField.setText("text/html");

        jLabel5.setText("SessionID:");

        cookieArea.setColumns(20);
        cookieArea.setRows(5);
        jScrollPane3.setViewportView(cookieArea);

        jLabel6.setText("Cookie:");

        jLabel7.setText("(  Filter:");

        contentTypeFilterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentTypeFilterFieldActionPerformed(evt);
            }
        });

        jLabel8.setText(")");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(charsetField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(sessionField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7)
                                .addGap(14, 14, 14)
                                .addComponent(contentTypeFilterField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(699, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(charsetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(contentTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sessionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(contentTypeFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void urlAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlAreaMouseClicked
        // TODO add your handling code here:
        String text = urlArea.getText();
        if (!"".equals(text)) {
            int pos = urlArea.getCaretPosition();
            int start = text.lastIndexOf("\n", pos);
            start = start >= 0 ? start : 0;
            int end = text.indexOf("\n", pos);
            String url = text.substring(start, end).trim();
            String mime = urlAndMIME.get(url);
            this.MIMEArea.setText(mime);
            this.MIMEArea.setCaretPosition(0);
        }
    }//GEN-LAST:event_urlAreaMouseClicked

    private void contentTypeFilterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentTypeFilterFieldActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_contentTypeFilterFieldActionPerformed

    public void clean() {
        this.urlArea.setText("");
        this.MIMEArea.setText("");
        this.cookieArea.setText("");
        this.sessionField.setText("");
        this.charsetField.setText("");
        this.contentTypeField.setText("");
    }

    public void update() {
        clean();
        IDocument doc = context.getBrowser().getDocument();
        String charset = doc.getCharSet();
        this.charsetField.setText(charset);
        String cookie = doc.getCookie();
        if (null != cookie) {
            String cookies[] = cookie.split(";");
            for (String c : cookies) {
                String temp = c.toLowerCase();
                if (temp.contains("session")) {
                    this.sessionField.setText(c);
                }
                this.cookieArea.append(c.trim());
                this.cookieArea.append(";\n");
            }
        }

        urlAndMIME = context.getURLAndMIME();
        Set<String> urls = urlAndMIME.keySet();

        String contentTypeFilter = this.contentTypeFilterField.getText();
        for (String url : urls) {
            boolean append = true;
            if (!"".equals(contentTypeFilter)) {
                if (url.indexOf(contentTypeFilter) < 0) {
                    append = false;
                }
            }
            if (append) {
                this.urlArea.append(url);
                this.urlArea.append("\n");
            }
        }
        String url = getLine(urlArea, 0);
        String mime = urlAndMIME.get(url);
        this.MIMEArea.setText(mime);
        this.cookieArea.setCaretPosition(0);
        this.urlArea.setCaretPosition(0);
        this.MIMEArea.setCaretPosition(0);
    }

    private String getLine(javax.swing.JTextArea area, int line) {
        try {
            int start = area.getLineStartOffset(line);
            int end = area.getLineEndOffset(line);
            return area.getText(start, end).trim();
        } catch (Exception ex) {
            return "";
        }
    }

    public void setContext(BrowserContext context) {
        this.context = context;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MIMEArea;
    private javax.swing.JTextField charsetField;
    private javax.swing.JTextField contentTypeField;
    private javax.swing.JTextField contentTypeFilterField;
    private javax.swing.JTextArea cookieArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField sessionField;
    private javax.swing.JTextArea urlArea;
    // End of variables declaration//GEN-END:variables
}
