/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnalysisPanel.java
 *
 * Created on Sep 13, 2011, 3:09:14 PM
 */
package websiteschema.analyzer.browser;

import com.webrenderer.swing.IMozillaBrowserCanvas;
import com.webrenderer.swing.dom.IElement;
import com.webrenderer.swing.dom.IElementCollection;
import java.net.URI;
import java.util.Date;
import websiteschema.cluster.DocumentConvertor;
import websiteschema.context.BrowserContext;
import websiteschema.element.XPathAttributes;
import websiteschema.model.domain.Site;
import websiteschema.model.domain.cluster.Sample;
import websiteschema.persistence.hbase.SampleMapper;
import websiteschema.utils.UrlLinkUtil;

/**
 *
 * @author ray
 */
public class AnalysisPanel extends javax.swing.JPanel {

    BrowserContext context;
    DocumentConvertor docConvertor = new DocumentConvertor();
    SimpleBrowser simpleBrowser = null;

    /** Creates new form AnalysisPanel */
    public AnalysisPanel(BrowserContext context, SimpleBrowser simpleBrowser) {
        initComponents();
        this.context = context;
        this.simpleBrowser = simpleBrowser;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sampleDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        siteIdField = new javax.swing.JTextField();
        viewSampleButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        addLinksButton = new javax.swing.JButton();
        viewCategoryButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        javax.swing.GroupLayout sampleDialogLayout = new javax.swing.GroupLayout(sampleDialog.getContentPane());
        sampleDialog.getContentPane().setLayout(sampleDialogLayout);
        sampleDialogLayout.setHorizontalGroup(
            sampleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        sampleDialogLayout.setVerticalGroup(
            sampleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(185, 32767));

        jLabel1.setText("网站ID : ");

        viewSampleButton.setText("查看样本");
        viewSampleButton.setToolTipText("查看并添加样本");

        addLinksButton.setText("自动添加样本");
        addLinksButton.setToolTipText("将页面上的所有链接添加为样本");
        addLinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLinksButtonActionPerformed(evt);
            }
        });

        viewCategoryButton.setText("查看分类");
        viewCategoryButton.setToolTipText("查看网站页面的分类");
        viewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(siteIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
            .addComponent(viewSampleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
            .addComponent(addLinksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
            .addComponent(viewCategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(siteIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSampleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLinksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewCategoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCategoryButtonActionPerformed

    private void addLinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLinksButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("addLinksButtonActionPerformed");
        IMozillaBrowserCanvas browser = context.getBrowser();
        IElementCollection links = browser.getDocument().getLinks();
        String pageUrl = context.getReference();
        String siteId = getSiteId();
        if (null != links && null != siteId && !"".equals(siteId)) {
            for (int i = 0; i < links.length(); i++) {
                IElement ele = links.item(i);
                String href = ele.getAttribute("href", 0);
                URI uri = UrlLinkUtil.getInstance().getURL(pageUrl, href);
                if ("http".equals(uri.getScheme())) {
                    context.getConsole().log("add sample: " + uri.getScheme() + ":" + uri.getSchemeSpecificPart());
                    addSampleUrl(uri.getScheme() + ":" + uri.getSchemeSpecificPart());
                }
            }
        } else {
            context.getMsgDialog().msg("can not get links or siteId is invalid.");
        }
    }//GEN-LAST:event_addLinksButtonActionPerformed

    private void addSampleUrl(String url) {
//        XPathAttributes attr = this.simpleBorwser.getXPathAttr();
//        this.docConvertor.setXpathAttr(attr);
        SampleMapper mapper = BrowserContext.getSpringContext().getBean("sampleMapper", SampleMapper.class);
        Sample sample = new Sample();
        String rowKey = getSiteId() + "+" + url;
        sample.setRowKey(rowKey);
        sample.setUrl(url);
        sample.setSiteId(getSiteId());
        sample.setCreateTime(new Date());
        mapper.put(sample);
    }

    public void setSiteId(String siteId) {
        this.siteIdField.setText(siteId);
    }

    public String getSiteId() {
        return this.siteIdField.getText().trim();
    }

    public void startAnalysis(Site site) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLinksButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JDialog sampleDialog;
    private javax.swing.JTextField siteIdField;
    private javax.swing.JButton viewCategoryButton;
    private javax.swing.JButton viewSampleButton;
    // End of variables declaration//GEN-END:variables
}
