/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VipsFrame.java
 *
 * Created on Aug 25, 2011, 11:34:22 AM
 */
package websiteschema.vips;

import java.awt.Canvas;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import websiteschema.vips.VipsCanvas;

/**
 *
 * @author ray
 */
public class VipsFrame extends javax.swing.JFrame {

    /** Creates new form VipsFrame */
    public VipsFrame() {
        initComponents();
        jScrollPane1.setVisible(true);
        JScrollBar hbar = jScrollPane1.getHorizontalScrollBar();   //   返回控制视图的水平视图位置的水平滚动条
        JScrollBar vbar = jScrollPane1.getVerticalScrollBar();    //   返回控制视图垂直视图位置的垂直滚动条
        hbar.addAdjustmentListener(new MyAdjustmentListener(this));
        vbar.addAdjustmentListener(new MyAdjustmentListener(this));
    }

    class MyAdjustmentListener implements AdjustmentListener {

        JFrame frame;
        int lastValue = 0;

        MyAdjustmentListener(JFrame frame) {
            this.frame = frame;
        }

        @Override
        public void adjustmentValueChanged(AdjustmentEvent e) {
            if (null != canvas1) {
                int value = e.getValue();
                int abs = value - lastValue;
                abs = abs > 0 ? abs : -abs;
//                if (abs > 50) {
                {
                    lastValue = value;
                    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
                    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
//                    System.out.println("reset scrollpane canvas.");
                    jScrollPane1.setViewportView(canvas1);
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VIPS Frame (Red is separator, and black is vision block)");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new VipsFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Canvas canvas1 = null;

    public Canvas getCanvas() {
        return canvas1;
    }

    public void setCanvas(Canvas canvas) {
        jScrollPane1.setViewportView(canvas);
        this.canvas1 = canvas;
    }

    public javax.swing.JScrollPane getScrollPane() {
        return jScrollPane1;
    }

    public void setVipsCanvasSize(int width, int height) {
        System.out.println("resize canvas size width: " + width + " height: " + height);
        canvas1.setSize(width, height);
    }
}
